
module.exports = {
    CHANGE_STATUS_SUCCESS: 'Cập nhật status thành công',
    CHANGE_STATUS_MULTI_SUCCESS: 'Có %d phần tử được cập nhật status thành công',
    CHANGE_ORDERING_SUCCESS: 'Cập nhật ordering thành công',
    DELETE_SUCCESS: 'Xóa phần tử thành công',
    DELETE_MULTI_SUCCESS: 'Có %d phần tử được xóa thành công',
    ADD_SUCCESS: 'Thêm mới phần tử thành công',
    EDIT_SUCCESS: 'Cập nhật thông tin phần tử thành công',
    ERROR_NAME: 'Chiều dài Name từ %d đến %d ký tự',
    ERROR_NAME_EMPTY: 'Name không được để trống',
    ERROR_TITLE_EMPTY: 'Tiêu đề không được để trống',
    // ERROR_ORDERING: 'Phải là số nguyên lớn hơn %d và bé hơn %d',
    ERROR_ORDERING: 'Ordering phải là số nguyên',
    ERROR_STATUS: 'Status phải là một giá trị khác rỗng',
    ERROR_Category: 'Vui lòng chọn Category',
    ERROR_SLUG: 'Slug không hợp lệ',
    ERROR_FILE_LIMIT: 'Kích thước file không phù hợp',
    ERROR_FILE_EXTENSION: 'Phần mở rộng file không hợp lệ',
    ERROR_FILE_EMPTY: 'Vui lòng chọn file hình',
    ERROR_LOGIN_USERNAME_NOTEXIST: 'Username không tồn tại',
    ERROR_LOGIN_PASSWORD_INCORRECT: 'Password không chính xác',
    ERROR_LOGIN: 'Thông tin đăng nhập không chính xác',
};